# Generated by Django 6.1.1 on 2026-10-05 19:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.PositiveIntegerField(editable=False, unique=True)),
                ('nome', models.CharField(max_length=120)),
                ('apelido', models.CharField(blank=True, max_length=60)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('ultimo_numero_nota', models.PositiveIntegerField(default=0, editable=False)),
                ('texto_busca', models.CharField(db_index=True, editable=False, max_length=200)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['texto_busca', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='Sequencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, unique=True)),
                ('valor', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('tipo', models.CharField(choices=[('UNICA', 'Única'), ('CONTINUA', 'Contínua')], max_length=10)),
                ('situacao', models.CharField(choices=[('RASCUNHO', 'Rascunho'), ('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('QUITADA', 'Quitada')], max_length=10)),
                ('criada_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('fechada_em', models.DateTimeField(blank=True, null=True)),
                ('quitada_em', models.DateTimeField(blank=True, null=True)),
                ('editada', models.BooleanField(default=False)),
                ('editada_em', models.DateTimeField(blank=True, null=True)),
                ('versao', models.PositiveIntegerField(default=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notas', to='fiado.cliente')),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['criada_em', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120)),
                ('quantidade', models.DecimalField(decimal_places=3, max_digits=9)),
                ('preco_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('adicionado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('adicionado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='fiado.nota')),
            ],
            options={
                'ordering': ['adicionado_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CorrecaoNota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feita_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('itens_anteriores', models.JSONField()),
                ('total_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('feita_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='correcoes', to='fiado.nota')),
            ],
            options={
                'ordering': ['feita_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forma', models.CharField(choices=[('DINHEIRO', 'Dinheiro'), ('PIX', 'Pix'), ('CARTAO', 'Cartão')], max_length=10)),
                ('recebido_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('lote', models.UUIDField(blank=True, db_index=True, null=True)),
                ('nota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='fiado.nota')),
                ('recebido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['recebido_em', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.UniqueConstraint(fields=('cliente', 'numero'), name='numero_unico_por_cliente'),
        ),
        migrations.AddConstraint(
            model_name='nota',
            constraint=models.UniqueConstraint(condition=models.Q(('situacao', 'ABERTA'), ('tipo', 'CONTINUA')), fields=('cliente',), name='uma_continua_aberta_por_cliente'),
        ),
    ]
